### ISSUE TITLE
Why not list unit-threaded as a dependency in dub.json?

### ISSUE THREAD

**Issue by AndrewGodfrey** [atilaneves/dtest#2]
I don't know if this is an issue, or something about dub I need to learn.
Anyway, I notice that dtest doesn't use dub's "dependencies" to list unit-threaded as a dependency. Why not? I see the "nodub" command-line option but it still seems like a weird way to manage the dependency.

Thanks!

**Comment by atilaneves** [comment]
Because it isn't a dependency, in the sense that it doesn't import it or link to it. The generated program depends on unit-threaded, however. Basically there are 2 runtimes, only the 2nd one has a dependency and dub.json is for the 1st runtime.
